# ansible/collections/requirements.yml
collections:
  - name: community.postgresql
    version: 4.1.0
  - name: networktocode.nautobot
    version: 5.16.1
  - name: ansible.posix
    version: 2.1.0
  - name: community.crypto
    version: 3.0.5
  - name: community.general
    version: 12.0.1