---
- name: Install a list of packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - git
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - redis-server

- name: Add official PostgreSQL repo
  ansible.builtin.file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: 0755

- name: Add Postgres Key and Repo
  block:
    - name: Download PostgreSQL signing key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc

    - name: Add PostgreSQL apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt noble-pgdg main"
        filename: pgdg
        state: present

- name: Install default PostgreSQL from OS repo
  ansible.builtin.apt:
    update_cache: yes
    name:
      - postgresql-{{ postgres_version }}
      - postgresql-client-{{ postgres_version }}
      - postgresql-common
      - redis-server
    state: present

- name: Ensure PostgreSQL is installed
  apt:
    name: "postgresql-{{ postgres_version }},postgresql-client-{{ postgres_version }}"
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure Postgres group exists
  ansible.builtin.group:
    name: postgres
    system: yes

- name: Ensure Postgres system user exists
  ansible.builtin.user:
    name: postgres
    comment: Postgres
    shell: /bin/bash
    home: /var/lib/postgresql
    system: yes

- name: Create Nautobot PostgreSQL database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: nautobot
    owner: postgres
    state: present
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: Create Postgres Nautobot user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: nautobot
    password: "{{ nautobot_db_password }}"
    role_attr_flags: LOGIN # CREATEDB,NOSUPERUSER
    state: present

- name: Grant all privileges on nautobot database to nautobot user
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: nautobot
    roles: nautobot
    type: database
    privs: ALL
    state: present

- name: Grant CREATE on public schema
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: nautobot
    roles: nautobot
    type: schema
    objs: public
    privs: CREATE
    state: present

- name: Ensure Nautobot group exists
  ansible.builtin.group:
    name: nautobot
    system: yes

- name: Create a nautobot system user
  ansible.builtin.user:
    name: nautobot
    comment: Nautobot
    create_home: true
    home: /home/nautobot
    system: true
    shell: /bin/bash

- name: Ensure Nautobot home directory has correct permissions
  ansible.builtin.file:
    path: /opt/nautobot
    owner: nautobot
    group: nautobot
    mode: "0755"
    state: directory

- name: Run a module inside a virtual environment
  block:
    - name: Ensure the virtual environment exists
      become_user: nautobot
      become: True
      ansible.builtin.pip:
        name:
          - pip
          - wheel
        virtualenv: /opt/nautobot/venv
        virtualenv_command: "python3 -m venv"
        virtualenv_site_packages: yes
        extra_args: --upgrade

    - name: Add NAUTOBOT_ROOT to the nautobot user .bashrc file
      ansible.builtin.lineinfile:
        path: /home/nautobot/.bashrc
        line: 'export NAUTOBOT_ROOT=/opt/nautobot'
        create: yes
        state: present
        owner: nautobot
        group: nautobot
        mode: '0644'

    - name: Install Nautobot for Postgres
      become_user: nautobot
      become: True
      ansible.builtin.pip:
        name: nautobot
        virtualenv: /opt/nautobot/venv
        extra_args: "--no-binary=pyuwsgi"