---
- name: Ensure PostgreSQL is installed
  ansible.builtin.apt:
    name: "postgresql-{{ postgres_version }},postgresql-client-{{ postgres_version }}"
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure Postgres group exists
  ansible.builtin.group:
    name: postgres
    system: yes

- name: Ensure Postgres system user exists
  ansible.builtin.user:
    name: postgres
    comment: Postgres
    shell: /bin/bash
    home: /var/lib/postgresql
    system: yes

- name: Create Nautobot PostgreSQL database
  #become_user: postgres
  community.postgresql.postgresql_db:
    name: nautobot
    owner: postgres
    state: present
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: Create Postgres Nautobot user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: nautobot
    password: "{{ nautobot_db_password }}"
    role_attr_flags: LOGIN # CREATEDB,NOSUPERUSER
    state: present

- name: Grant all privileges on nautobot database to nautobot user
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: nautobot
    roles: nautobot
    type: database
    privs: ALL
    state: present

- name: Grant CREATE on public schema
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: nautobot
    roles: nautobot
    type: schema
    objs: public
    privs: CREATE
    state: present